blank_issues_enabled: false
contact_links:
  - name: Report an issue on GitLab.com
    url: https://gitlab.com/notpushkin/mkdocutils/-/issues
    about: You can sign in with your GitHub account easily.
